In [23]:
from numpy import array
from keras.preprocessing.text import Tokenizer
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import SimpleRNN

import tensorflow as tf
import numpy as np

In [24]:
# source text
data = """Tesla is an American multinational automotive and clean energy company headquartered in Austin, Texas.\n
 Tesla designs and manufactures electric vehicles (electric cars and trucks), battery energy storage from home to grid-scale, solar panels and solar roof tiles, and related products and services. \n
 Tesla is one of the world's most valuable companies and is, as of 2023, the world's most valuable automaker. \n
 In 2021, the company had the most worldwide sales of battery electric vehicles and plug-in electric vehicles,\n
  capturing 21% of the battery-electric (purely electric) market and 14% of the plug-in market (which includes plug-in hybrids). \n
  Through its subsidiary Tesla Energy, the company develops and is a major installer of photovoltaic systems in the United States.\n
   Tesla Energy is also one of the largest global suppliers of battery energy storage systems, with 3.99 gigawatt-hours (GWh) installed in 2021."""

In [25]:
# integer encode text
tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])
encoded_data= tokenizer.texts_to_sequences([data])[0]
encoded_data

[6,
 7,
 22,
 23,
 24,
 25,
 1,
 26,
 8,
 10,
 27,
 4,
 28,
 29,
 6,
 30,
 1,
 31,
 5,
 11,
 5,
 32,
 1,
 33,
 9,
 8,
 14,
 34,
 35,
 36,
 37,
 38,
 15,
 39,
 1,
 15,
 40,
 41,
 1,
 42,
 43,
 1,
 44,
 6,
 7,
 16,
 3,
 2,
 17,
 12,
 18,
 45,
 1,
 7,
 46,
 3,
 47,
 2,
 17,
 12,
 18,
 48,
 4,
 19,
 2,
 10,
 49,
 2,
 12,
 50,
 51,
 3,
 9,
 5,
 11,
 1,
 13,
 4,
 5,
 11,
 52,
 53,
 3,
 2,
 9,
 5,
 54,
 5,
 20,
 1,
 55,
 3,
 2,
 13,
 4,
 20,
 56,
 57,
 13,
 4,
 58,
 59,
 60,
 61,
 6,
 8,
 2,
 10,
 62,
 1,
 7,
 63,
 64,
 65,
 3,
 66,
 21,
 4,
 2,
 67,
 68,
 6,
 8,
 7,
 69,
 16,
 3,
 2,
 70,
 71,
 72,
 3,
 9,
 8,
 14,
 21,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 4,
 19]

In [26]:
# determine the vocabulary size
vocab_size = len(tokenizer.word_index) + 1  # 0 is reserved for padding so that's why we added 1

print('Vocabulary Size: %d' % vocab_size)

Vocabulary Size: 80


In [27]:
# create word -> word sequences
sequences = list()
for i in range(1, len(encoded_data)):
	sequence = encoded_data[i-1:i+1]
	sequences.append(sequence)
print('Total Sequences: %d' % len(sequences))
# split into X and y elements

Total Sequences: 144


In [28]:
sequences
#sequences[:5] # [input, output]

[[6, 7],
 [7, 22],
 [22, 23],
 [23, 24],
 [24, 25],
 [25, 1],
 [1, 26],
 [26, 8],
 [8, 10],
 [10, 27],
 [27, 4],
 [4, 28],
 [28, 29],
 [29, 6],
 [6, 30],
 [30, 1],
 [1, 31],
 [31, 5],
 [5, 11],
 [11, 5],
 [5, 32],
 [32, 1],
 [1, 33],
 [33, 9],
 [9, 8],
 [8, 14],
 [14, 34],
 [34, 35],
 [35, 36],
 [36, 37],
 [37, 38],
 [38, 15],
 [15, 39],
 [39, 1],
 [1, 15],
 [15, 40],
 [40, 41],
 [41, 1],
 [1, 42],
 [42, 43],
 [43, 1],
 [1, 44],
 [44, 6],
 [6, 7],
 [7, 16],
 [16, 3],
 [3, 2],
 [2, 17],
 [17, 12],
 [12, 18],
 [18, 45],
 [45, 1],
 [1, 7],
 [7, 46],
 [46, 3],
 [3, 47],
 [47, 2],
 [2, 17],
 [17, 12],
 [12, 18],
 [18, 48],
 [48, 4],
 [4, 19],
 [19, 2],
 [2, 10],
 [10, 49],
 [49, 2],
 [2, 12],
 [12, 50],
 [50, 51],
 [51, 3],
 [3, 9],
 [9, 5],
 [5, 11],
 [11, 1],
 [1, 13],
 [13, 4],
 [4, 5],
 [5, 11],
 [11, 52],
 [52, 53],
 [53, 3],
 [3, 2],
 [2, 9],
 [9, 5],
 [5, 54],
 [54, 5],
 [5, 20],
 [20, 1],
 [1, 55],
 [55, 3],
 [3, 2],
 [2, 13],
 [13, 4],
 [4, 20],
 [20, 56],
 [56, 57],
 [57, 13],
 [1

In [29]:
sequences = array(sequences)
X, y = sequences[:,0],sequences[:,1]

In [30]:
X[:5]

array([ 6,  7, 22, 23, 24])

In [31]:
y[:5]

array([ 7, 22, 23, 24, 25])

In [32]:
# one hot encode outputs
y = to_categorical(y, num_classes=vocab_size)
# define model
y[:5]

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [33]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=1))
model.add(SimpleRNN(50))
model.add(Dense(vocab_size, activation='softmax'))
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 1, 10)             800       
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 50)                3050      
                                                                 
 dense_1 (Dense)             (None, 80)                4080      
                                                                 
Total params: 7,930
Trainable params: 7,930
Non-trainable params: 0
_________________________________________________________________
None


In [34]:
# compile network
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [35]:
# fit network
model.fit(X, y, epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 5ms/step - loss: 4.3805 - accuracy: 0.0139
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 4.3721 - accuracy: 0.0486
Epoch 3/100
5/5 [==============================] - 0s 4ms/step - loss: 4.3648 - accuracy: 0.1111
Epoch 4/100
5/5 [==============================] - 0s 4ms/step - loss: 4.3571 - accuracy: 0.1528
Epoch 5/100
5/5 [==============================] - 0s 4ms/step - loss: 4.3491 - accuracy: 0.1458
Epoch 6/100
5/5 [==============================] - 0s 4ms/step - loss: 4.3405 - accuracy: 0.1806
Epoch 7/100
5/5 [==============================] - 0s 4ms/step - loss: 4.3316 - accuracy: 0.1667
Epoch 8/100
5/5 [==============================] - 0s 4ms/step - loss: 4.3214 - accuracy: 0.1597
Epoch 9/100
5/5 [==============================] - 0s 4ms/step - loss: 4.3095 - accuracy: 0.1597
Epoch 10/100
5/5 [==============================] - 0s 3ms/step - loss: 4.2973 - accuracy: 0.1667
Epoch 11/100
5/5 [===========

In [36]:
encoded = tokenizer.texts_to_sequences(['Tesla'])[0]
encoded = array(encoded)

In [37]:
encoded


array([6])

In [38]:
yhat = model.predict(encoded)

1/1 [==============================] - 0s 162ms/step


In [39]:
yhat.argmax(axis=1)


array([8])

In [40]:
# generate a sequence from the model
def generate_seq(model, tokenizer, enter_text, n_pred):  
	in_text, result = enter_text, enter_text  # 
	# generate a fixed number of words
	for _ in range(n_pred):
        
		# encode the text as integer
		encoded = tokenizer.texts_to_sequences([in_text])[0]
		encoded = array(encoded)
        
		# predict a word in the vocabulary
		yhat = model.predict(encoded)
        
		# map predicted word index to word
		out_word = ''
		for word, index in tokenizer.word_index.items():
			if index == yhat.argmax(axis=1):
				out_word = word
				break
		# append to input
		in_text, result = out_word, result + ' ' + out_word
	return result

In [41]:
# evaluate
print(generate_seq(model, tokenizer, 'Tesla', 10))


1/1 [==============================] - 0s 23ms/step
Tesla energy storage systems in 2021 the world's most valuable automaker
